CREATE TABLE `CCDB`.`USER` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `phone` VARCHAR(45) NULL,
  `password` VARCHAR(200) NULL,
  
  PRIMARY KEY (`id`));

  